### ISSUE TITLE
Designate Code of Conduct enforcement group

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/rfcs#21]
[RFC 17](https://github.com/web-platform-tests/rfcs/pull/17) presents an incomplete Code of Conduct for WPT. It lacks contact information for individuals who are responsible for enforcing the code, and this is because we haven't found anyone to help out.

In order to complete that RFC (and resubmit the proposal), we need to identify a group of people who would be willing to provide this service to WPT. This issue is intended to track progress towards that goal.

**Comment by jugglinmike** [comment]
Some initial questions:

- how many people should be on the team?
- where/how should we solicit volunteers?

**Comment by gsnedders** [comment]
We also should define some process as to what happens when a report a received.

I don't think we need a huge number of people, but we do need a decent number; I'd probably suggest half a dozen.

**Comment by foolip** [comment]
This repo is for tracking high-level changes in WPT, so perhaps we can consider this issue announcement enough?

I'd suggest that whoever wants to drive https://github.com/web-platform-tests/rfcs/pull/17 to completion also reaches out to candidates. There will be a chance to self-nominate or object on the RFC itself.

**Comment by gsnedders** [comment]
@foolip but we closed the RFC because it doesn't have any changes from the earlier PR?

**Comment by foolip** [comment]
@gsnedders right, just saying that whoever wants to push that through the RFC process should self-assign this first. @jugglinmike or was your expectation that the wpt core team would resolve this issue so that you can reopen #17?

**Comment by jugglinmike** [comment]
I closed gh-17 based on @gsnedders' indication that the proposal required substantive work before it could be considered complete. Since the process is designed to facilitate discussion on concrete proposals, the RFC should only be re-opened once such a list is available.

It's a little unclear whether or not someone outside of the core team can/should find volunteers, but only because the core team has not indicated support of a Code of Conduct, generally. It's probably a safe bet that they do, but this issue is partly intended to provoke dissent if it exists.

An alternative would be to create yet another RFC: "Search for Volunteers to Enforce Code of Conduct," but I assumed that would be more process than is useful.

**Comment by gsnedders** [comment]
> I closed [gh-17](https://github.com/web-platform-tests/rfcs/pull/17) based on @gsnedders' indication that the proposal required substantive work before it could be considered complete. Since the process is designed to facilitate discussion on concrete proposals, the RFC should only be re-opened once such a list is available.

I'm not sure how much of the substantive work needs to be deal with at the RFC level. I don't think we need huge guidelines as to how to deal with reports, and I don't think we need the core team's agreement on every last detail. The largest part is finding volunteers for volunteers.

**Comment by foolip** [comment]
Yeah, finding volunteers and writing words seems like the time consuming bit here. I'd be surprised if there's any dissent from the core team or from elsewhere.

**Comment by jugglinmike** [comment]
Agreed on all accounts. The "substantive work" I referenced is exactly finding the volunteers.

**Comment by boazsender** [comment]
I would be happy to volunteer on to be a reporting contact for the code of conduct.

I'm also available starting the week of April 8th to work on updating the CoC itself. I just worked on the re-write of the [Bocoup Code of Conduct](https://bocoup.com/code-of-conduct), and have volunteered to work with the @jorydotcom and the TC39 CoC group as a point of conduct for the new Ecma TC53 CoC.

Let me know how else I can help.

**Comment by foolip** [comment]
@boazsender sounds great! Would you be up for finding whatever number of volunteers you think is appropriate and eventually reopen #17? If so I can assign this issue to you :)

**Comment by jorydotcom** [comment]
echoing @boazsender here - happy to help. There are some efforts brewing within TC39 and other community spaces to create a supportive 'playbook' of sorts, would be great to get ya'lls input on those resources as they come together as well!

**Comment by boazsender** [comment]
Sure thing @foolip. I'm heading out of the office tomorrow, but will take that up when I'm back the week of April 15th.

**Comment by boazsender** [comment]
Sorry for the long delay on this. I think we're fine to move forward with two folks on the enforcement group:

* Boaz Sender (@boazsender)
* Jory Burson (@jorydotcom)

Can you reassign #17 to me so I can reopen it?

I've opened https://github.com/web-platform-tests/wpt/pull/18948 with patch to add the contributor covenant with Jory and myself as points of contact for enforcement.

**Comment by frivoal** [comment]
Nice, thanks for picking this up (and sorry for not noticing earlier). A couple of comments:

* I'd suggest indicating next to the names of the moderators which languages they are comfortable communicating in. If someone who's not fluent in English feels the need to reach out to moderators, they are likely to feel more at ease if they find someone who can speak their language.
* I'd also move the names/means of contacting the moderators to the top, with a clear/short message, to make it really obvious and easy to find, including to people who have a hard time reading a long chunk of text in English, and/or might be in a distressing situation which could affect their willingness/ability to read through the hole thing.

* WPT is a collaborative project that involves, among others, W3C and WHATWG. We should probably add a statement that in situations / communication channels that can be considered both WPT and W3C/WHATWG, we will operate under both/all the code of conducts. For example, if there's a WPT related meeting at TPAC, people will be expected to respect both the WPT code of conduct and the W3C's. Largely, they boil down to the same thing, but we shouldn't leave the window open for trouble makers to claim that certain behavior banned (for instance) by WPT but allowed by W3C is ok because this was a test meeting at TPAC and therefore WPT's code of conduct doesn't count, or vice versa. Note: The W3C's Advisory Board has considered the same question for joint WHATWG/W3C events, and we favor this "both CoC apply" approach. Also, you may wish to coordinate with the W3C's [Positive Work Environment CG](https://www.w3.org/community/pwe/), who's responsible for evolving the W3C's code of conduct, as they may have useful feedback.

**Comment by gsnedders** [comment]
The other thing that came out of discussion at TPAC is having a defined process for how we add people to the group.

**Comment by stephenmcgruer** [comment]
As per https://github.com/web-platform-tests/rfcs/pull/17#issuecomment-614370614, @boazsender no longer has time to work on this so I am removing him from the assignee list.

Reading this thread and the RFC, I come up with the below (incomplete) summary of Things Needing Done. Most of these involve changing the RFC, a few involve updating the [Code of Conduct PR](https://github.com/web-platform-tests/wpt/pull/7520).

**Enforcement Team**
- Define minimum and desirable size of the team. @gsnedders suggested ~6 as the desirable size, @boazsender suggested we could move forward (at least for now?) with 2 members.
- Define initial members of the team; @boazsender had suggested themselves and @jorydotcom . We need to reaffirm their desire to be involved given the time that has passed, and also consider who else might be an appropriate member (if necessary).

**Processes**
- Define a process for someone to be added to the enforcement team. I note that in a brief search, I was unable to find an equivalent to this in the Rust CoC or the WHATWG CoC. The W3C Code of Ethics and Professional Conduct technically defines this as their 'enforcement team' appears to be the same Ombuds used for all complain resolution, which has an existing process for membership.
- Define guidance for handling complaints. It's not clear to me what is expected here beyond what is already in the existing [Code of Conduct PR](https://github.com/web-platform-tests/wpt/pull/7520) (which defines warning before temporary removal before permanent removal). Again in a brief search I was not able to find anything more substantial in Rust/WHATWG/W3C.

**Editorial**
- Move contact details to the top of the [Code of Conduct PR](https://github.com/web-platform-tests/wpt/pull/7520), or otherwise make it quick to get from the top to the people who can be contacted.
- Add known languages to the enforcement team list in the [Code of Conduct PR](https://github.com/web-platform-tests/wpt/pull/7520)
- Make it clear that in a situation where multiple Code of Conducts apply, WPT expects people to abide by the union of the Code of Conducts (and that if you feel the CoCs conflict, contact the WPT moderators). (Again I note that I cannot find similar language in the WHATWG, W3C, etc CoCs.)

**Comment by guest271314** [comment]
What will "Enforcement Team" do when W3C, WHATWG,  WICG, or any other organization, including itself, does not abide by its own code of conduct? 

Is the concept merely big  Me  and little You?

Not everybody needs a group hug and not everyone speaks the same language.

Learned long ago, via hard lessons, that there is  no such thing as  "respect", objectively. "respect" is an emotion that the individual evokes from within themselves and "gives". However, "respect" has no definitive meaning, start or ending. An individual could "respect" another one moment and revoke that sentiment in the next moment. Kindly exclude the term "respect" from any "code of conduct" unless you can define the term without an emotional component - which you cannot. Also, "rude" is another term that should not be included in any "code of coduct".

Any conduct on this board is trivial compared to conduct of individuals on boards long ago shut down by gov'ment. Some of these would-be purists would not have lasted a day in those realms, and Mod Squad was heavy-handed - though not as heavy-handed as the sensitive, emotion-driven moderators of today. In fact, if you actually post facts,  citing primary sources at each post, they might make the wild accusation that you are a Russian bot! That has actually occurred to this user more than once, on more than one site. Because own domain and range, from decades of studying various disciplines are outside of the wheelhouse of some inddividuals and institutions, they just ban, suspend indefinitely, or in the case of WICG, impose an absurb 1,000  year ban 
![Screenshot_2020-04-26_17-35-11](https://user-images.githubusercontent.com/4174848/80314979-51a0b000-87e4-11ea-99af-5b820278aa85.png)
for using the "real name" guest271314. WICG, and W3C claimed that guest271314 is not a "real name" when joined those organizations at their suggestion. Yet, they never defined the term "real name" in any of their voluminous documents. Example of one hypocritical action by the W3C organization ![72086389-bcde7900-32fe-11ea-82c1-8cbff2901fce](https://user-images.githubusercontent.com/4174848/80314905-f8d11780-87e3-11ea-914c-c8e32c180f92.png). It took a while for them to clearly state that "IPR" meant "Intellectual Property Rights" to them. 

Whatever you do: don't be hypocrites. Don't think you own language or can arbitrarily decide by virtue of being some would-be august body that you can state that X word is "offensive" or Y word is not "offensive", or be a hall monitor, or deal with emotions rather than facts. If you say something, do it. Keep your word https://lists.w3.org/Archives/Public/public-wicg/2019Oct/0000.html. Really, moderators should say as little as possible.

**Comment by gsnedders** [comment]
@guest271314 This isn't an appropriate venue to vent your issues about with other groups with other policies about banning users, whether they have a CoC or not. At this point, essentially the whole project is in favour of the CoC, plenty chance to object has been given, and almost no objections have been raised.

Ultimately, people are free to fork the project if they feel how it is being run by the Core Team makes them unable to contribute; the Core Team have influence insofar as they represent the bodies paying for many of the largest contributors and hence have the time on their side, but their influence is weak beyond that. If a fork is sufficiently advantageous, I don't doubt vendors would start importing tests from there.

**Comment by guest271314** [comment]
@gsnedders You don't get it. And you probably never will. Did not ask for your permission to give you an expert opinion on the potential for fraudulent conduct under the auspices of a "Code of Conduct" by the very individuals who might set up such a Gestapo system that are accountable to no one. In some venues all it takes is one objection to halt a proposal. Do not expect that here. Individuals are hell bent on closing issues, banning users - excluding themselves from scrutiny - because,  after all they are "Core Team".

What you fail to realize is that do not give a damn about what you consider to be "respect" - either wanting or needing your "respect" or attempting to appease what could amount to your individual sensitivities or emotions. Am not here to be liked, make friends or agree with a proposition because all of the individuals who think they are cool kids are doing it. 

If you  took your erroneous emotional evaluation out of the post out of the equation, you might be able to illuminate yourself to some things to avoid once this supposed "Code of Conduct" is cast in stone. Each time have been banned or suspended there are hypocrites and frandulent behaviour and conduct by the very individuals and institutions who point to their supposed "Code of Conduct" as some gospel. Don't be hypocrites and frauds like have experienced, if you can. Though, once individuals start talking about a "Code of Conduct" they need to test it out, find a sacrificial byte to run through the xor gate; create an algorithm and then blame the algorithm for doing stuff. We'll see. 

> Ultimately, people are free to fork the project if they feel how it is being run by the Core Team makes them unable to contribute

That is simply false. 

"feel" has nothing to do with computing. 

Do not care about your emotional state or what you "feel". 

Rely on the scientific method. This is about computing and technology, not making you or anyone else "feel" a certain way. Groups hugs have been banned in public anyway since they released the virus they created into the public.

**Comment by gsnedders** [comment]
>  Define minimum and desirable size of the team. @gsnedders suggested ~6 as the desirable size, @boazsender suggested we could move forward (at least for now?) with 2 members.

FWIW, I had at least one other volunteer whom I should check in on. That said, I'm not overly concerned about the size of the group (IIRC, my motivation before was mostly fear out of management chains affecting people's willingness to come forth, but at least Jory avoids that).

> Define a process for someone to be added to the enforcement team. I note that in a brief search, I was unable to find an equivalent to this in the Rust CoC or the WHATWG CoC. The W3C Code of Ethics and Professional Conduct technically defines this as their 'enforcement team' appears to be the same Ombuds used for all complain resolution, which has an existing process for membership.

I don't think we really need to define a process here? Very few groups define such a thing because enforcement is very much variable depending on availability of potential moderators and in what space the infraction occurs (especially in meatspace).

**Comment by stephenmcgruer** [comment]
> FWIW, I had at least one other volunteer whom I should check in on. That said, I'm not overly concerned about the size of the group (IIRC, my motivation before was mostly fear out of management chains affecting people's willingness to come forth, but at least Jory avoids that).

If you could check with them, that would be appreciated. I similarly don't think we need a specific size mentioned, but would much prefer 3+ to 2+.

**Comment by gsnedders** [comment]
> If you could check with them, that would be appreciated. I similarly don't think we need a specific size mentioned, but would much prefer 3+ to 2+.

They asked their manager, and have now pinged said manager. I have no further update to provide. Also remembered someone else I think I pinged and asked them again.

**Comment by gsnedders** [comment]
> Also remembered someone else I think I pinged and asked them again.

`group.push(` @nsatragno `)`

**Comment by stephenmcgruer** [comment]
> group.push( @nsatragno )

Done.

**Comment by stephenmcgruer** [comment]
We now have a 3 person moderator team, which I think meets the minimum we would want, and I've addressed the action items I filed in https://github.com/web-platform-tests/rfcs/issues/21#issuecomment-615283331, so I think this issue has run its course. The RFC has been updated and shifted to https://github.com/web-platform-tests/rfcs/pull/54, and comments on it are very welcome there :).
